services:
  simpler-products-app:
    build: . 
    ports:
      - "8080:8080"
    depends_on:
      mysql-db:
        condition: service_healthy

  mysql-db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=products_db
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=pass!
    volumes:
      - ./mysql-data:/var/lib/mysql
