name: CI/CD Pipeline

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.23'
    - name: Install dependencies
      run: make install-deps
    - name: Run tests
      run: make test
  
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.23'
    - name: Install dependencies
      run: make install-deps
    - name: Lint
      run: make lint
    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.53.3
        args: --no-config --disable-all --enable gocritic,gofumpt

  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.23'
    - name: Format
      run: |
        make fmt
        if [ -n "$(git status --porcelain)" ]; then
          echo "Code formatting changes detected. Please run 'go fmt' and commit the changes."
          exit 1
        fi

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.23'
    - name: Install dependencies
      run: make install-deps
    - name: Build
      run: make build

  vulnerability-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Scan for vulnerabilities
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true 